services:
  backend:
    image: ${DOCKER_REGISTRY-}backend
    build:
      context: .
      dockerfile: src/Backend/Dockerfile
    environment:
      - DeskApi__BaseUrl=http://box-simulator:8000/api/v2/E9Y2LxT4g1hQZ7aD8nR3mWx5P0qK6pV7/
    depends_on:
      postgres:
        condition: service_healthy
      box-simulator:
        condition: service_started

  mosquitto:
    container_name: mqtt
    image: eclipse-mosquitto
    command:
      - "/usr/sbin/mosquitto"
      - "-c"
      - "/mosquitto/config/mosquitto.conf"
      - "-v"
    ports:
      - "1883:1883"
      - "9001:9001" # Secured connection isn't configured correctly
    volumes:
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/config:/mosquitto/config
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped

  box-simulator:
    hostname: box-simulator
    build:
      context: .
      dockerfile: infra/docker/simulator.Dockerfile
    container_name: box-simulator
    ports:
      - "8000:8000"
    volumes:
      - simulator_data:/app/data
    restart: unless-stopped

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: semester_project_3
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d semester_project_3"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    image: dpage/pgadmin4
    ports:
      - "6050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    configs:
      - source: servers_config
        target: /pgadmin4/servers.json   

    
volumes:
  postgres_data:
  pgadmin_data:
  simulator_data:

configs:
  servers_config:
    content: |
      {
        "Servers": {
          "1": {
            "Group": "Servers",
            "Name": "postgres",
            "Host": "postgres",
            "Port": 5432,
            "MaintenanceDB": "postgres",
            "Username": "postgres",
            "Password": "postgres",
            "SSLMode": "prefer"
          }
        }
      }