services:
  backend:
    image: ${DOCKER_REGISTRY-}backend
    build:
      context: .
      dockerfile: src/Backend/Dockerfile

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: semester_project_3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    image: dpage/pgadmin4
    ports:
      - "6050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    configs:
      - source: servers_config
        target: /pgadmin4/servers.json   

    
volumes:
  postgres_data:
  pgadmin_data:

configs:
  servers_config:
    content: |
      {
        "Servers": {
          "1": {
            "Group": "Servers",
            "Name": "postgres",
            "Host": "postgres",
            "Port": 5432,
            "MaintenanceDB": "postgres",
            "Username": "postgres",
            "Password": "postgres",
            "SSLMode": "prefer"
          }
        }
      }