services:
  react-main:
    build:
      context: ../../src/group1.sem3.frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: https://s3-be-main.michalvalko.eu/api
    container_name: react-main
    ports:
      - "3000:80"
    restart: unless-stopped

  react-integrate:
    build:
      context: ../../src/group1.sem3.frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: https://s3-be-int.michalvalko.eu/api
    container_name: react-integrate
    ports:
      - "3001:80"
    restart: unless-stopped

  react-develop:
    build:
      context: ../../src/group1.sem3.frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: https://s3-be-dev.michalvalko.eu/api
    container_name: react-develop
    ports:
      - "3002:80"
    restart: unless-stopped

